name: release new version

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm install pnpm -g
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
