name: release new version

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install pnpm -g
      - run: git config --global user.email ${{secrets.USER_EMAIL}}
      - run: git config --global user.name ${{secrets.USER_NAME}}
      - run: pnpm install
      - run: pnpm build
      - run: pnpm release
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
